# Application Settings
application:
  name: my-app
  version: 1.0.0
  environment: production

server:
  host: 0.0.0.0
  port: 8080
  timeout: 30s

database:
  type: postgresql
  host: db.example.com
  port: 5432
  name: myapp_prod
  ssl: true 