apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-files-assecrets-example
type: Opaque
data:
  # Convert files to Secret format (Base64 encoded)
  {{- $secretFiles := .Files.Glob "secrets/*" }}
  {{- if $secretFiles }}
{{ $secretFiles.AsSecrets | indent 2 }}
  {{- end }}
  
  # Include config files as secrets
  {{- $configFiles := .Files.Glob "config/*.txt" }}
  {{- if $configFiles }}
{{ $configFiles.AsSecrets | indent 2 }}
  {{- end }} 